release-date = "2025-12-05"

[[entries]]
id = "92764a7f-617d-46e3-8898-8ffeeff41f94"
type = "fix"
description = "Bump PDM to 2.26.1 to fix build errors due to Hishel's refactoring"
author = "matthieu.antoine@helsing.ai"

[[entries]]
id = "f809b28c-cbc7-4ff6-8165-66111c517715"
type = "docs"
description = "Replace outdated reference to PEX in docstring"
author = "scott@stevenson.io"

[[entries]]
id = "4bb64abf-06bd-43bc-8162-e264604f5e9a"
type = "improvement"
description = "Add python.ty to type check with Ty"
author = "thomas.pellissier-tanon@helsing.ai"

[[entries]]
id = "d43aec5f-48b0-4946-9ab1-6739a8584acf"
type = "fix"
description = "Fix PyPI index check"
author = "John-P@users.noreply.github.com"

[[entries]]
id = "375cdbe9-468e-46b4-ba58-bbb8b852ed4f"
type = "fix"
description = "Fixed Python publish task failing with \"Property is finalized\" error when `skip_existing=True`"
author = "John-P@users.noreply.github.com"
