[[entries]]
id = "bb5bfd14-bfc6-432b-ad01-c45bb8948183"
type = "breaking change"
description = "Remove deprecated `--save`, `--resume` and `--restart` graph options and corresponding serialization code"
author = "@NiklasRosenstein"

[[entries]]
id = "9f42b55c-eec9-46e1-9c49-f21307478fea"
type = "breaking change"
description = "Remove `mkdocs.build` and `mkdocs.serve` task, there is only `mkdocs` now and if you want to serve the docs instead you need to use `krakenw run :mkdocs --serve`"
author = "@NiklasRosenstein"
