[tools]
"pipx:kraken-wrapper" = "0.45.1"
"pipx:mksync" = "0.1.4"
"pipx:pdm" = "2.25.4"
"pipx:poetry" = "2.1.3"
"pipx:slap-cli" = "1.15.0"
typos = "1.34.0"
uv = "0.7.20"

[tasks.build-docs]
run = "uv run --project kraken-build kraken invoke mkdocs --no-strict -vv"
