[project]
dependencies = [
  "kraken-wrapper",
  "kraken-build",
]
description = "Add your description here"
name = "examples"
readme = "README.md"
version = "0.1.0"

[tool.uv.sources]
kraken-build = {path = "../kraken-build", editable = true}
kraken-wrapper = {path = "../kraken-wrapper", editable = true}
