[[entries]]
id = "799ecb3d-0755-4004-9ac5-de6b8b4e1dae"
type = "feature"
description = "Add `Graph.task(ok)` argument and `Graph.get_status()`"
author = "@NiklasRosenstein"

[[entries]]
id = "7e612ad1-f65a-412c-bc19-3888b2adc8a9"
type = "feature"
description = "Add `Supplier.get_or_else()`"
author = "@NiklasRosenstein"
