site_name: Kraken
repo_url: https://github.com/kraken-build/kraken
repo_name: kraken-build/kraken
theme:
  name: material
  palette:
    primary: blue
    accent: green
  # features:
  #   - navigation.tabs

hooks:
  - mksync-hook.py

plugins:
  - search
  - mkdocstrings:
      default_handler: python_xref
      handlers:
        python_xref:
          paths:
            - ../kraken-build/src
            - ../kraken-wrapper/src
          # inventories:
          # - https://docs.python.org/3/objects.inv
          options:
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            separate_signature: true
            show_signature_annotations: true
            relative_crossrefs: true
            scoped_crossrefs: true
            docstring_section_style: list

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - changelog.md
  - Concepts:
    - concepts/tasks.md
    - concepts/properties.md
    - concepts/testing.md
  - Language support:
    - lang/cargo.md
    - lang/docker.md
    - lang/helm.md
    - lang/python.md
  - API Documentation:
    - kraken:
      - api/kraken/build.md
      - "common":
        - api/kraken/common/index.md
        - api/kraken/common/graphviz.md
        - api/kraken/common/findpython.md
        - api/kraken/common/supplier.md
      - "core":
          - api/kraken/core/index.md
          - api/kraken/core/address.md
          - "system":
            - api/kraken/core/system/aspect.md
            - api/kraken/core/system/buildcache.md
            - api/kraken/core/system/context.md
            - api/kraken/core/system/errors.md
            - api/kraken/core/system/graph.md
            - api/kraken/core/system/kraken_object.md
            - api/kraken/core/system/project.md
            - api/kraken/core/system/property.md
            - api/kraken/core/system/task_supplier.md
            - api/kraken/core/system/task.md
      - "std":
        - api/kraken/std/aws.md
        - api/kraken/std/buffrs.md
        - api/kraken/std/cargo.md
        - api/kraken/std/dist.md
        - api/kraken/std/docs.md
        - api/kraken/std/git.md
        - api/kraken/std/helm.md
        - api/kraken/std/mitm.md
        - api/kraken/std/python.md
        - api/kraken/std/sccache.md
        - api/kraken/std/shellcheck.md
        - api/kraken/std/util.md
        - "descriptors":
          - api/kraken/std/descriptors/resource.md
  - Command-line:
    - cli/kraken-query-describe.md
    - cli/kraken-query-env.md
    - cli/kraken-query-ls.md
    - cli/kraken-query-tree.md
    - cli/kraken-query-visualize.md
    - cli/kraken-query.md
    - cli/kraken-run.md
    - cli/kraken.md
  - krakenw.md
