name: Run example

on:
  workflow_call:
    inputs:
      example-name:
        description: 'The name of the example to run.'
        required: true
        type: string
      command:
        description: 'The command to run.'
        required: true
        type: string
      python-version:
        description: 'The version of Python to use.'
        required: false
        type: string
        default: '3.13'
      krakenw:
        description: 'Whether to run with krakenw'
        required: false
        type: boolean
        default: true

jobs:
  kraken:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          python-version: ${{ inputs.python-version }}
      - name: Install Kraken
        run: uv tool install -e ./kraken-build
      - name: Run Example
        working-directory: examples/${{ inputs.example-name }}
        run: kraken ${{ inputs.command }} -vv

  krakenw:
    runs-on: ubuntu-latest
    if: ${{ inputs.krakenw }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          python-version: ${{ inputs.python-version }}
      - name: Install Kraken
        run: uv tool install -e ./kraken-wrapper
      - name: Run Example
        working-directory: examples/${{ inputs.example-name }}
        run: krakenw ${{ inputs.command }} -vv
