name: Examples

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "*" ] }

env:
  COLUMNS: 200

jobs:
  run-example:
    uses: ./.github/workflows/.run-example.yaml
    strategy:
      fail-fast: false
      matrix:
        example-name:
          - aws-lambda
          - docker
          - docker-manual
    name: ${{ matrix.example-name }}
    with:
      example-name: ${{ matrix.example-name }}
      command: run :**

  run-examples-with-aspects:
    uses: ./.github/workflows/.run-example.yaml
    strategy:
      fail-fast: false
      matrix:
        include:
          - example-name: aws-lambda
            command: build :lambda --outfile out.zip --no-symlink
    name: ${{ matrix.example-name }} (aspect)
    with:
      example-name: ${{ matrix.example-name }}
      command: ${{ matrix.command }}
      krakenw: false
