name: Run examples

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "*" ] }

jobs:
  run-example:
    uses: ./.github/workflows/run-example.yml
    with:
      example-name: aws-lambda
      targets: lambda
